name: Prod CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Publish
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: DiscordMusicBot.Runner/Dockerfile
          tags: puddlebuddy/puddle-bot
        
